### ISSUE TITLE
Support git namespaces

### ISSUE THREAD

**Issue by kim** [radicle-dev/radicle-surf#101]
radicle-dev/radicle-link#144 will hand out surf `Browser`s on a per-namespace basis. That is, the `librad` user should not be able to surf the monorepo, but only the logical repo (namespace) it asked for.

While `libgit2` can set a namespace per-`git2::Repository`, this a) does not work as advertised ("This namespace affects all reference operations for the repo.") and b) is global state if we share the `git2::Repository` (see #100), which is problematic.

What could work is to construct a `Browser` with an optional namespace, and implement `list_branches` in terms of [`references`](https://docs.rs/git2/0.13.5/git2/struct.Repository.html#method.references) instead of `branches`.

**Comment by cloudhead** [comment]
This is what we need to complete radicle-dev/radicle-upstream#289

Are there other changes that would need to be made to the API (besides from `list_branches`), for things like blobs, commits, trees etc. to all work within the context of a namespace?

I'm also wondering if it makes sense to allow `Browser` to set its namespace post-construction, eg. `browser.namespace("blah")`, as this may come in handy if Browser construction is expensive (maybe it isn't).
