### ISSUE TITLE
Get last commit for a path

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-surf#11]
A common use case we have is to know the last commit which touched a blob or a tree (for git repos). This information is shown contextually in the code browsing views.

![ss](https://user-images.githubusercontent.com/1585/69436357-86926d80-0d41-11ea-97d7-b20e4533bda0.png)

A command which has served us so far to retrieve the sha1 of such a commit is:

```
git rev-list -n 1 HEAD --branches master -- "src/path.rs"
```

/cc @rudolfs

**Comment by FintanH** [comment]
#18 added this :)

**Comment by xla** [comment]
Extra Dope!
