### ISSUE TITLE
Project Stats

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-surf#124]
Implement a function for the browser that gives the stats for some project. The stats include:
* Number of branches
* Number of commits - presumably the number of commits on the current branch you're browsing
* Number of contributors - should this number be based on the default branch (which needs to be fixed on #115) or on the current branch you're browsing?

**Comment by cloudhead** [comment]
> Number of contributors - should this number be based on the default branch (which needs to be fixed on #115) or on the current branch you're browsing?

Branch you're browsing, same for commit count.

**Comment by FintanH** [comment]
Ah, I just dropped a comment on the PR :smile: Cool that sounds good to me and makes things simpler

**Comment by FintanH** [comment]
Closed via #125
