### ISSUE TITLE
Organise git objects

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-surf#14]
Currently we just use [`Reference`](https://docs.rs/git2/0.10.1/git2/struct.Reference.html) for all our git object needs. It would be more useful for the end user to think about the more common objects of branches, tags, commits, and revs

**Comment by xla** [comment]
An overview that helped me when looking deeper into git objects and how to model them was the [Git Community Book](http://shafiul.github.io/gitbook/1_the_git_object_model.html).

**Comment by FintanH** [comment]
Closed via #20
