### ISSUE TITLE
Depend on workspace version of crates

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-surf#178]
While we want to be able to publish to crates.io we also want to enable usage of workspace versions of crates when developing, for that we need to add the `path` key as well as the version to in the Cargo.toml:

https://github.com/radicle-dev/radicle-surf/blob/883f8d243cca35035d0d1ff076992b302aa0ac0c/source/Cargo.toml#L27-L29

**Comment by FintanH** [comment]
Do you know if that's possible? :thinking:

**Comment by xla** [comment]
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations

**Comment by FintanH** [comment]
Awesome :) Their example isn't that clear :sweat_smile:
