### ISSUE TITLE
Remote branches containing slashes are not listed.

### ISSUE THREAD

**Issue by geigerzaehler** [radicle-dev/radicle-surf#191]
Assume we have a repo with the following ref: `refs/remotes/banana/orange/lemon`. I’d expect `orange/lemon` to be included in the result of
```rust
browser.list_branches(BranchSelector::Remote { name: Some("banana".to_string()) })?;
```
The current behavior is that `orange/lemon` is not included.

The culprit is the single star glob `*` at the end [here](https://github.com/radicle-dev/radicle-surf/blob/f1f1cb7ce1ccec080cd99189bf9388a46dcbd8e9/surf/src/vcs/git/reference/glob.rs#L122-L126). Changing this to a double-start glob is not straight-forward though. This would also mean that the internal `rad/self` branches are listed by `radicle-source`.

**Comment by FintanH** [comment]
I beg to differ :upside_down_face: https://github.com/radicle-dev/radicle-surf/pull/194

Could it be the case that this happens when we're under a namespace?

**Comment by geigerzaehler** [comment]
#194 passes because we’re using `BranchSelector::All`. This uses `**` as the remote in the glob `refs/namespaces/<ns>/**/*`. And this coincidentally matches all branches. If we use `BranchSelector::Remote` (like [we do in upstream](https://github.com/radicle-dev/radicle-upstream/blob/a1de9e5e53d8eb04018fe3744300b757841ce60d/proxy/api/src/http/source.rs#L165)) branches with slashes are not listed. I created a failing test case in #195.

**Comment by FintanH** [comment]
Ah perfect, thanks for creating the failing case!

**Comment by FintanH** [comment]
I believe it might actually be a parsing issue in the `TryFrom` impl for `Branch`

**Comment by geigerzaehler** [comment]
False alarm. This does actually work: https://github.com/radicle-dev/radicle-surf/blob/eff4cf3d9685f9eb051c864c00b62bbeb21da7a9/surf/src/vcs/git.rs#L1218-L1221

Seems like me problem originated from somewhere else.
