### ISSUE TITLE
Design doc: meaning of Location?

### ISSUE THREAD

**Issue by gh1dra** [radicle-dev/radicle-surf#2]
In the design document, for defining the `Change` type we have constructors:

```haskell
AddLineToFile :: FileName -> Location -> FileContents -> Change
RemoveLineFromFile :: FileName -> Location -> Change
```

It's implied that `Location` is a line number(?) when looking at `buildChangeMap` handling cases of adding or removing changes using a given commit;  but what if we wanted to remove multiple lines in a single commit? Adding lines looks correct to me since it's supplied a `FileContents` and appends to wherever its specified.

**Comment by gh1dra** [comment]
We could change this to be `[Location]` where in the case of adding content we can enforce the property of it only having one element in the list

**Comment by FintanH** [comment]
So you may notice that a `Commit` has a `[Change]` so it allows us to change multiple `Location`s in one commit. However, something I ended up opting for simplicity-sake in the code base is to say that `Addition` just mutates `FileContents`. I didn't want to keep track of the diffs at this stage. It will be something that we will want to keep track of for the viewer though.

**Comment by gh1dra** [comment]
Ah makes sense, thanks for the clarification.

**Comment by FintanH** [comment]
@gh1dra you may interested in the redesign of the semantics in #6
