### ISSUE TITLE
`cargo fmt` dropped support for `license_template_path`

### ISSUE THREAD

**Issue by sebastinez** [radicle-dev/radicle-surf#206]
It seemed that rustfmt dropped support for `license_template_path` here https://github.com/rust-lang/rustfmt/pull/5246
So I'm thinking we should remove it from `.rustfmt.toml` and maybe replace it with some own fmt script?
https://github.com/radicle-dev/radicle-surf/blob/77b1905ba38fc9c95c01c0ed09d4d495548eacc2/.rustfmt.toml#L31

**Comment by FintanH** [comment]
That's fair. We actually also dropped this in radicle-link, I believe. We just have to be Diligent:tm:

**Comment by FintanH** [comment]
Fixed in https://github.com/radicle-dev/radicle-surf/commit/b85d2183d786e5fa447aab9d2f420a32f1061bfa
