### ISSUE TITLE
When retrieving branches origin/HEAD is returned

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-surf#29]
What's the meaning of `origin/HEAD` when calling `list_branches`? In git `HEAD` is the symbolic reference which points to the tip of the current branch, or detached when checking out a tag. I don't think there is such a thing as a `HEAD` for a remote.

**Comment by kim** [comment]
The example uses a submodule. So I guess it means that submodules are weird 🍭 

The submodule having a `HEAD` symbolic ref makes sense, as it is checked out at a specific revision. Not sure why that is below `refs/remotes/origin`, tho

**Comment by FintanH** [comment]
When I ran `git branch --remotes` it comes up as `origin/HEAD -> origin/master`

I also found this answer: https://superuser.com/questions/1192865/git-what-does-an-extra-item-origin-head-mean

So it seems to be the pointer to the `HEAD` of the remote, i.e. the default branch

**Comment by xla** [comment]
@FintanH Would it be safe to assume to treat it as the ref that informs about the remote branch then? And in turn where should we transform this information then? As in can we annotate a branch with the information if it is the default one and drop `origin/HEAD` from the returned list?

If this is out-of-scope of **surf** we can push this up to the consumer level.

**Comment by FintanH** [comment]
Well something that we're able to do is filter by local and remote branches. So I could expose this filter as well and then when it's `Remote` + `HEAD` we can filter it out?

**Comment by xla** [comment]
Come to think of it, filtering is one part of it. But more interesting does the current API allow to get what the branch/ref is pointing to? This would be helpful to get the default branch info.

**Comment by xla** [comment]
> Well something that we're able to do is filter by local and remote branches. So I could expose this filter as well and then when it's `Remote` + `HEAD` we can filter it out?

I think this could work, not quite sure if we lose anything valuable with that.

**Comment by kim** [comment]
The fact that the remote HEAD is preserved is specific to submodules, you won’t see that for normal remotes.

I’m not sure if you want to filter out remote branches entirely, but you may want to group them separately from local ones - when looking at some contribution, the user will want to browse remote branches.

**Comment by FintanH** [comment]
> The fact that the remote HEAD is preserved is specific to submodules, you won’t see that for normal remotes.

I'm not so sure. If you run `git branch --remote` in a repository you have you'll see this entry `origin/HEAD -> origin/master` in the list.

> I’m not sure if you want to filter out remote branches entirely, but you may want to group them separately from local ones - when looking at some contribution, the user will want to browse remote branches.

I wasn't suggestion filtering them out completely. There's the option of filtering _by_ remote or local. So you pass in this `BranchType` value to view one or the other, and `None` if you want to see all :)

**Comment by kim** [comment]
On Tuesday, December 10, 2019, Fintan Halpenny <notifications@github.com>
wrote:

> The fact that the remote HEAD is preserved is specific to submodules, you
> won’t see that for normal remotes.
>
> I'm not so sure. If you run git branch --remote in a repository you have
> you'll see this entry origin/HEAD -> origin/master in the list.
>

Mysterious - I don’t see this. Maybe it’s something GitHub changed, and
they’re now advertising `origin/HEAD`?

**Comment by xla** [comment]
I can reproduce what @FintanH described on a local checkout of the radicle-upstream repo.

**Comment by FintanH** [comment]
Ya, I tried a completely unrelated repo that doesn't have any submodules
