### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by xla** [radicle-dev/radicle-surf#33]
When "implementing" #30 I ran into the issue that the required submodule for test fixtures wasn't present. To avoid surprises it would be helpful to have contribution guidelines in the README or in a separate CONTRIBUTING.md. Another approach to consider is to codify such steps in a `build.rs`.

**Comment by FintanH** [comment]
I like both the idea of a `CONTRIBUTING.md` _and_ a `build.rs`. I just need to look into `build.rs` first :smile:
