### ISSUE TITLE
Into impl for Path

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-surf#37]
Improve the `Path` ergonomics by implementing `impl Into<Path> for `Vec<Label>`

**Comment by FintanH** [comment]
The initial description is poorly formed (I was so naive in 2019...), the correct implementation should look more like:

```rust
impl From<Path> for Vec<Label>
```

What I'm not quite sure about is if that's ok if our module doesn't own `Vec` but does own `Path`.

**Comment by xla** [comment]
> The initial description is poorly formed (I was so naive in 2019...), the correct implementation should look more like:

So 2019 of you...
