### ISSUE TITLE
Smart Revisions

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-surf#55]
Currently it's a bit verbose for users to select a generic revision: https://github.com/radicle-dev/radicle-upstream/blob/master/proxy/src/schema/mod.rs#L174-L177

Let's get smart.

**Comment by xla** [comment]
The [revparse](https://docs.rs/git2/0.11.0/git2/struct.Repository.html#method.revparse) method could be of help realising this feature.
