### ISSUE TITLE
Commit History

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-surf#64]
View the commit history of a file or directory.

The majority of this work is done via `last_commit`, we just need to make the functionality `pub`.

**Comment by cloudhead** [comment]
This is a β2 feature actually. We only need tree history for β1, which we already have.

**Comment by FintanH** [comment]
@cloudhead: can you explain what you mean by "tree history"?

Also, I think this would be trivial to provide because the change is simple. If the UI wanted to provide that view in the near future :)

**Comment by cloudhead** [comment]
I mean repository/global history.
