### ISSUE TITLE
Error Libraries and Practices

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-surf#76]
Following [these conventions](https://rust-lang.github.io/api-guidelines/interoperability.html#error-types-are-meaningful-and-well-behaved-c-good-err) as well as our own radicle-dev/radicle-decisions#2.

We should use `thiserror` and make some errors more opaque and consistent.

**Comment by FintanH** [comment]
The last thing to do is add `non_exhaustive`

**Comment by sonro** [comment]
I can update this.

**Comment by FintanH** [comment]
Thanks! I should have remembered when I was reviewing :sweat_smile:
