### ISSUE TITLE
A File's contents should be something better than String

### ISSUE THREAD

**Issue by FintanH** [radicle-dev/radicle-surf#8]
See discussion here: https://github.com/radicle-dev/radicle-surf/pull/7#discussion_r346785490

A `File`'s contents are currently `String` but we should have something closer to bytes. The `diff` logic will likely drive this decision.

**Comment by FintanH** [comment]
#10 changes this to a `Vec<u8>`

**Comment by xla** [comment]
> `Vec<u8>`

classy
