### ISSUE TITLE
Branch information inside `Commit` object

### ISSUE THREAD

**Issue by cloudhead** [radicle-dev/radicle-surf#94]
For the application, we are going to need to know which branch a given commit is in. Interestingly, a commit can be in multiple branches. If this is the case, we need to pick one branch, but I'm not sure what kind of heuristic we can use here, except checking if the commit is part of the default branch. Looking at the GitHub UI, it only ever shows one branch per commit.

Perhaps this isn't surf's concern and it can at least for now just return the output of `git branch --contains <commit>`.

**Comment by xla** [comment]
Just for reference Github UI also shows a tag and release the commit is included in. The contains option sounds like a helpful building block and leaves opinions up to the caller

**Comment by FintanH** [comment]
Ya, I'm not sure I'd put _inside_ the `Commit` object, but rather provide a function `Commit -> Vec<Branch>` (or `NonEmpty` if that's possible).

**Comment by cloudhead** [comment]
Yeah that also works!
